title: Bertilla Fabris
logo: "/images/B.jpg?raw=true"
description:
  Computer Science Master student
  with a focus on Information Architecture
  and Agent-Based Modelling
  
theme: jekyll-theme-minimal
