title: Bertilla Fabris
logo: "/images/B.jpg?raw=true"
description:
  Doctoral student at Umeå University, Sweden.
  Researching Critical Healthcare with Agent-Based Modelling and Social Simulations.
  
theme: jekyll-theme-minimal